{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from fhir_client import FHIRClient\n",
    "import logging\n",
    "import pandas as pd\n",
    "logging.basicConfig(level=logging.INFO)\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "import preprocessing\n",
    "\n",
    "\n",
    "client = FHIRClient(service_base_url='https://r3.smarthealthit.org', preprocessor=preprocessing, logger=logger)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:root:Received 18117 procedures in 60.80 seconds.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>code</th>\n",
       "      <th>display</th>\n",
       "      <th>system</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>893</th>\n",
       "      <td>183450002</td>\n",
       "      <td>Admission to burn unit</td>\n",
       "      <td>http://snomed.info/sct</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1911</th>\n",
       "      <td>305340004</td>\n",
       "      <td>Admission to long stay hospital</td>\n",
       "      <td>http://snomed.info/sct</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>83</th>\n",
       "      <td>305428000</td>\n",
       "      <td>Admission to orthopedic department</td>\n",
       "      <td>http://snomed.info/sct</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6217</th>\n",
       "      <td>305433001</td>\n",
       "      <td>Admission to trauma surgery department</td>\n",
       "      <td>http://snomed.info/sct</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13687</th>\n",
       "      <td>35637008</td>\n",
       "      <td>Alcohol rehabilitation</td>\n",
       "      <td>http://snomed.info/sct</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            code                                 display  \\\n",
       "893    183450002                  Admission to burn unit   \n",
       "1911   305340004         Admission to long stay hospital   \n",
       "83     305428000      Admission to orthopedic department   \n",
       "6217   305433001  Admission to trauma surgery department   \n",
       "13687   35637008                  Alcohol rehabilitation   \n",
       "\n",
       "                       system  \n",
       "893    http://snomed.info/sct  \n",
       "1911   http://snomed.info/sct  \n",
       "83     http://snomed.info/sct  \n",
       "6217   http://snomed.info/sct  \n",
       "13687  http://snomed.info/sct  "
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "procedures = client.get_all_procedures()\n",
    "pd.DataFrame([prod.code['coding'][0] for prod in procedures]).drop_duplicates().sort_values(by=['display']).head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "conditions = client.get_all_conditions()\n",
    "pd.DataFrame([cond.code['coding'][0] for cond in conditions]).drop_duplicates().sort_values(by=['display']).head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:root:Received 43 observations in 0.24 seconds.\n",
      "INFO:root:Received 41 observations in 0.37 seconds.\n",
      "INFO:root:Received 21 observations in 0.19 seconds.\n",
      "INFO:root:Received 16 observations in 0.22 seconds.\n",
      "INFO:root:Received 181 observations in 1.12 seconds.\n",
      "INFO:root:Received 36 observations in 0.30 seconds.\n",
      "INFO:root:Received 49 observations in 0.31 seconds.\n",
      "INFO:root:Received 21 observations in 0.20 seconds.\n",
      "INFO:root:Received 139 observations in 0.72 seconds.\n",
      "INFO:root:Received 58 observations in 0.43 seconds.\n",
      "INFO:root:Received 135 observations in 0.53 seconds.\n",
      "INFO:root:Received 42 observations in 0.27 seconds.\n",
      "INFO:root:Received 29 observations in 0.31 seconds.\n",
      "INFO:root:Received 118 observations in 0.58 seconds.\n",
      "INFO:root:Received 41 observations in 0.33 seconds.\n",
      "INFO:root:Received 43 observations in 0.55 seconds.\n",
      "INFO:root:Received 23 observations in 0.17 seconds.\n",
      "INFO:root:Received 53 observations in 0.49 seconds.\n",
      "INFO:root:Received 56 observations in 0.44 seconds.\n",
      "INFO:root:Received 154 observations in 0.91 seconds.\n",
      "INFO:root:Received 37 observations in 0.18 seconds.\n",
      "INFO:root:Received 30 observations in 0.33 seconds.\n",
      "INFO:root:Received 56 observations in 0.42 seconds.\n",
      "INFO:root:Received 41 observations in 0.23 seconds.\n",
      "INFO:root:Received 66 observations in 0.43 seconds.\n",
      "INFO:root:Received 34 observations in 0.39 seconds.\n",
      "INFO:root:Received 62 observations in 0.48 seconds.\n",
      "INFO:root:Received 29 observations in 0.19 seconds.\n",
      "INFO:root:Received 45 observations in 0.18 seconds.\n",
      "INFO:root:Received 55 observations in 0.53 seconds.\n",
      "INFO:root:Received 71 observations in 0.38 seconds.\n",
      "INFO:root:Received 60 observations in 0.55 seconds.\n",
      "INFO:root:Received 49 observations in 0.24 seconds.\n",
      "INFO:root:Received 46 observations in 0.24 seconds.\n",
      "INFO:root:Received 18 observations in 0.18 seconds.\n",
      "INFO:root:Received 54 observations in 0.44 seconds.\n",
      "INFO:root:Received 27 observations in 0.56 seconds.\n",
      "INFO:root:Received 24 observations in 0.24 seconds.\n",
      "INFO:root:Received 99 observations in 0.60 seconds.\n",
      "INFO:root:Received 111 observations in 0.72 seconds.\n",
      "INFO:root:Received 33 observations in 0.21 seconds.\n",
      "INFO:root:Received 47 observations in 0.44 seconds.\n",
      "INFO:root:Received 125 observations in 0.91 seconds.\n",
      "INFO:root:Received 72 observations in 0.45 seconds.\n",
      "INFO:root:Received 54 observations in 0.36 seconds.\n",
      "INFO:root:Received 48 observations in 0.43 seconds.\n",
      "INFO:root:Received 25 observations in 0.18 seconds.\n",
      "INFO:root:Received 113 observations in 0.56 seconds.\n",
      "INFO:root:Received 38 observations in 0.22 seconds.\n",
      "INFO:root:Received 48 observations in 0.22 seconds.\n",
      "INFO:root:Received 33 observations in 0.20 seconds.\n",
      "INFO:root:Received 43 observations in 0.16 seconds.\n",
      "INFO:root:Received 178 observations in 0.80 seconds.\n",
      "INFO:root:Received 51 observations in 0.48 seconds.\n",
      "INFO:root:Received 37 observations in 0.26 seconds.\n",
      "INFO:root:Received 39 observations in 0.20 seconds.\n",
      "INFO:root:Received 45 observations in 0.21 seconds.\n",
      "INFO:root:Received 42 observations in 0.47 seconds.\n",
      "INFO:root:Received 39 observations in 0.31 seconds.\n",
      "INFO:root:Received 42 observations in 0.22 seconds.\n",
      "INFO:root:Received 58 observations in 0.51 seconds.\n",
      "INFO:root:Received 21 observations in 0.19 seconds.\n",
      "INFO:root:Received 61 observations in 0.43 seconds.\n",
      "INFO:root:Received 139 observations in 0.59 seconds.\n",
      "INFO:root:Received 17 observations in 0.20 seconds.\n",
      "INFO:root:Received 25 observations in 0.19 seconds.\n",
      "INFO:root:Received 47 observations in 0.21 seconds.\n",
      "INFO:root:Received 50 observations in 0.65 seconds.\n",
      "INFO:root:Received 58 observations in 0.60 seconds.\n",
      "INFO:root:Received 100 observations in 0.45 seconds.\n",
      "INFO:root:Received 54 observations in 0.34 seconds.\n",
      "INFO:root:Received 25 observations in 0.26 seconds.\n",
      "INFO:root:Received 46 observations in 0.21 seconds.\n",
      "INFO:root:Received 54 observations in 0.57 seconds.\n",
      "INFO:root:Received 29 observations in 0.19 seconds.\n",
      "INFO:root:Received 52 observations in 0.41 seconds.\n",
      "INFO:root:Received 41 observations in 0.21 seconds.\n",
      "INFO:root:Received 37 observations in 0.20 seconds.\n",
      "INFO:root:Received 52 observations in 0.34 seconds.\n",
      "INFO:root:Received 204 observations in 1.41 seconds.\n",
      "INFO:root:Received 35 observations in 0.24 seconds.\n",
      "INFO:root:Received 31 observations in 0.21 seconds.\n",
      "INFO:root:Received 64 observations in 0.47 seconds.\n",
      "INFO:root:Received 26 observations in 0.20 seconds.\n",
      "INFO:root:Received 43 observations in 0.18 seconds.\n",
      "INFO:root:Received 143 observations in 0.71 seconds.\n",
      "INFO:root:Received 43 observations in 0.21 seconds.\n",
      "INFO:root:Received 45 observations in 0.21 seconds.\n",
      "INFO:root:Received 21 observations in 0.17 seconds.\n",
      "INFO:root:Received 48 observations in 0.35 seconds.\n",
      "INFO:root:Received 38 observations in 0.20 seconds.\n",
      "INFO:root:Received 48 observations in 0.18 seconds.\n",
      "INFO:root:Received 164 observations in 0.68 seconds.\n",
      "INFO:root:Received 25 observations in 0.17 seconds.\n",
      "INFO:root:Received 37 observations in 0.19 seconds.\n",
      "INFO:root:Received 155 observations in 0.83 seconds.\n",
      "INFO:root:Received 96 observations in 0.39 seconds.\n",
      "INFO:root:Received 34 observations in 0.19 seconds.\n",
      "INFO:root:Received 35 observations in 0.20 seconds.\n",
      "INFO:root:Received 17 observations in 0.17 seconds.\n",
      "INFO:root:Received 51 observations in 0.27 seconds.\n",
      "INFO:root:Received 69 observations in 0.37 seconds.\n",
      "INFO:root:Received 30 observations in 0.18 seconds.\n",
      "INFO:root:Received 66 observations in 0.36 seconds.\n",
      "INFO:root:Received 139 observations in 0.56 seconds.\n",
      "INFO:root:Received 43 observations in 0.26 seconds.\n",
      "INFO:root:Received 30 observations in 0.17 seconds.\n",
      "INFO:root:Received 17 observations in 0.17 seconds.\n",
      "INFO:root:Received 42 observations in 0.23 seconds.\n",
      "INFO:root:Received 21 observations in 0.17 seconds.\n",
      "INFO:root:Received 69 observations in 0.35 seconds.\n",
      "INFO:root:Received 44 observations in 0.38 seconds.\n",
      "INFO:root:Received 118 observations in 0.64 seconds.\n",
      "INFO:root:Received 42 observations in 0.35 seconds.\n",
      "INFO:root:Received 33 observations in 0.20 seconds.\n",
      "INFO:root:Received 50 observations in 0.42 seconds.\n",
      "INFO:root:Received 16 observations in 0.18 seconds.\n",
      "INFO:root:Received 33 observations in 0.21 seconds.\n",
      "INFO:root:Received 34 observations in 0.21 seconds.\n",
      "INFO:root:Received 154 observations in 0.65 seconds.\n",
      "INFO:root:Received 50 observations in 0.28 seconds.\n",
      "INFO:root:Received 65 observations in 0.43 seconds.\n",
      "INFO:root:Received 65 observations in 0.32 seconds.\n",
      "INFO:root:Received 27 observations in 0.18 seconds.\n",
      "INFO:root:Received 46 observations in 0.29 seconds.\n",
      "INFO:root:Received 62 observations in 0.29 seconds.\n",
      "INFO:root:Received 58 observations in 0.33 seconds.\n",
      "INFO:root:Received 165 observations in 0.71 seconds.\n",
      "INFO:root:Received 26 observations in 0.14 seconds.\n",
      "INFO:root:Received 60 observations in 0.28 seconds.\n",
      "INFO:root:Received 31 observations in 0.18 seconds.\n",
      "INFO:root:Received 40 observations in 0.19 seconds.\n",
      "INFO:root:Received 35 observations in 0.18 seconds.\n",
      "INFO:root:Received 120 observations in 0.49 seconds.\n",
      "INFO:root:Received 21 observations in 0.22 seconds.\n",
      "INFO:root:Received 49 observations in 0.21 seconds.\n",
      "INFO:root:Received 195 observations in 1.02 seconds.\n",
      "INFO:root:Received 48 observations in 0.20 seconds.\n",
      "INFO:root:Received 33 observations in 0.18 seconds.\n",
      "INFO:root:Received 154 observations in 1.11 seconds.\n",
      "INFO:root:Received 149 observations in 0.61 seconds.\n",
      "INFO:root:Received 43 observations in 0.17 seconds.\n",
      "INFO:root:Received 62 observations in 0.66 seconds.\n",
      "INFO:root:Received 25 observations in 0.18 seconds.\n",
      "INFO:root:Received 20 observations in 0.21 seconds.\n",
      "INFO:root:Received 35 observations in 0.19 seconds.\n",
      "INFO:root:Received 20 observations in 0.22 seconds.\n",
      "INFO:root:Received 48 observations in 0.20 seconds.\n",
      "INFO:root:Received 68 observations in 0.54 seconds.\n",
      "INFO:root:Received 43 observations in 0.19 seconds.\n",
      "INFO:root:Received 155 observations in 3.56 seconds.\n",
      "INFO:root:Received 126 observations in 0.62 seconds.\n",
      "INFO:root:Received 46 observations in 0.40 seconds.\n",
      "INFO:root:Received 47 observations in 0.21 seconds.\n",
      "INFO:root:Received 90 observations in 0.54 seconds.\n",
      "INFO:root:Received 203 observations in 1.04 seconds.\n",
      "INFO:root:Received 13 observations in 0.16 seconds.\n",
      "INFO:root:Received 14 observations in 0.17 seconds.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:root:Received 29 observations in 0.19 seconds.\n",
      "INFO:root:Received 204 observations in 0.77 seconds.\n",
      "INFO:root:Received 63 observations in 0.40 seconds.\n",
      "INFO:root:Received 34 observations in 0.19 seconds.\n",
      "INFO:root:Received 67 observations in 0.43 seconds.\n",
      "INFO:root:Received 31 observations in 0.18 seconds.\n",
      "INFO:root:Received 53 observations in 0.32 seconds.\n",
      "INFO:root:Received 153 observations in 0.65 seconds.\n",
      "INFO:root:Received 25 observations in 0.17 seconds.\n",
      "INFO:root:Received 22 observations in 0.17 seconds.\n",
      "INFO:root:Received 86 observations in 0.36 seconds.\n",
      "INFO:root:Received 42 observations in 0.20 seconds.\n",
      "INFO:root:Received 154 observations in 0.68 seconds.\n",
      "INFO:root:Received 20 observations in 0.19 seconds.\n",
      "INFO:root:Received 71 observations in 0.34 seconds.\n",
      "INFO:root:Received 34 observations in 0.19 seconds.\n",
      "INFO:root:Received 58 observations in 0.32 seconds.\n",
      "INFO:root:Received 55 observations in 0.42 seconds.\n",
      "INFO:root:Received 38 observations in 0.26 seconds.\n",
      "INFO:root:Received 35 observations in 0.19 seconds.\n",
      "INFO:root:Received 37 observations in 0.19 seconds.\n",
      "INFO:root:Received 57 observations in 0.34 seconds.\n",
      "INFO:root:Received 29 observations in 0.19 seconds.\n",
      "INFO:root:Received 17 observations in 0.16 seconds.\n",
      "INFO:root:Received 42 observations in 0.45 seconds.\n",
      "INFO:root:Received 81 observations in 0.44 seconds.\n",
      "INFO:root:Received 48 observations in 0.17 seconds.\n",
      "INFO:root:Received 90 observations in 0.36 seconds.\n",
      "INFO:root:Received 155 observations in 0.66 seconds.\n",
      "INFO:root:Received 38 observations in 0.20 seconds.\n",
      "INFO:root:Received 139 observations in 0.60 seconds.\n",
      "INFO:root:Received 26 observations in 0.17 seconds.\n",
      "INFO:root:Received 42 observations in 0.21 seconds.\n",
      "INFO:root:Received 18 observations in 0.17 seconds.\n",
      "INFO:root:Received 41 observations in 0.20 seconds.\n",
      "INFO:root:Received 34 observations in 0.17 seconds.\n",
      "INFO:root:Received 69 observations in 0.32 seconds.\n",
      "INFO:root:Received 60 observations in 0.35 seconds.\n",
      "INFO:root:Received 44 observations in 0.25 seconds.\n",
      "INFO:root:Received 69 observations in 0.61 seconds.\n",
      "INFO:root:Received 153 observations in 0.63 seconds.\n",
      "INFO:root:Received 43 observations in 0.21 seconds.\n",
      "INFO:root:Received 56 observations in 0.31 seconds.\n",
      "INFO:root:Received 41 observations in 0.31 seconds.\n",
      "INFO:root:Received 201 observations in 0.92 seconds.\n",
      "INFO:root:Received 13 observations in 0.19 seconds.\n",
      "INFO:root:Received 25 observations in 0.17 seconds.\n",
      "INFO:root:Received 38 observations in 0.19 seconds.\n",
      "INFO:root:Received 13 observations in 0.16 seconds.\n",
      "INFO:root:Received 38 observations in 0.16 seconds.\n",
      "INFO:root:Received 58 observations in 0.54 seconds.\n",
      "INFO:root:Received 53 observations in 0.31 seconds.\n",
      "INFO:root:Received 21 observations in 0.17 seconds.\n",
      "INFO:root:Received 43 observations in 0.19 seconds.\n",
      "INFO:root:Received 29 observations in 0.17 seconds.\n",
      "INFO:root:Received 28 observations in 0.18 seconds.\n",
      "INFO:root:Received 165 observations in 0.64 seconds.\n",
      "INFO:root:Received 139 observations in 0.56 seconds.\n",
      "INFO:root:Received 57 observations in 0.32 seconds.\n",
      "INFO:root:Received 37 observations in 0.35 seconds.\n",
      "INFO:root:Received 22 observations in 0.18 seconds.\n",
      "INFO:root:Received 143 observations in 0.51 seconds.\n",
      "INFO:root:Received 21 observations in 0.18 seconds.\n",
      "INFO:root:Received 106 observations in 0.69 seconds.\n",
      "INFO:root:Received 30 observations in 0.34 seconds.\n",
      "INFO:root:Received 149 observations in 0.53 seconds.\n",
      "INFO:root:Received 65 observations in 0.28 seconds.\n",
      "INFO:root:Received 25 observations in 0.17 seconds.\n",
      "INFO:root:Received 55 observations in 0.31 seconds.\n",
      "INFO:root:Received 69 observations in 0.37 seconds.\n",
      "INFO:root:Received 159 observations in 0.61 seconds.\n",
      "INFO:root:Received 37 observations in 0.18 seconds.\n",
      "INFO:root:Received 44 observations in 0.20 seconds.\n",
      "INFO:root:Received 29 observations in 0.17 seconds.\n",
      "INFO:root:Received 49 observations in 0.19 seconds.\n",
      "INFO:root:Received 50 observations in 0.20 seconds.\n",
      "INFO:root:Received 130 observations in 0.49 seconds.\n",
      "INFO:root:Received 29 observations in 0.28 seconds.\n",
      "INFO:root:Received 17 observations in 0.16 seconds.\n",
      "INFO:root:Received 58 observations in 0.32 seconds.\n",
      "INFO:root:Received 13 observations in 0.37 seconds.\n",
      "INFO:root:Received 42 observations in 0.19 seconds.\n",
      "INFO:root:Received 112 observations in 0.77 seconds.\n",
      "INFO:root:Received 21 observations in 0.33 seconds.\n",
      "INFO:root:Received 46 observations in 0.19 seconds.\n",
      "INFO:root:Received 38 observations in 0.19 seconds.\n",
      "INFO:root:Received 42 observations in 0.19 seconds.\n",
      "INFO:root:Received 23 observations in 0.17 seconds.\n",
      "INFO:root:Received 57 observations in 0.32 seconds.\n",
      "INFO:root:Received 63 observations in 0.31 seconds.\n",
      "INFO:root:Received 24 observations in 0.17 seconds.\n",
      "INFO:root:Received 29 observations in 0.18 seconds.\n",
      "INFO:root:Received 41 observations in 0.44 seconds.\n",
      "INFO:root:Received 201 observations in 0.76 seconds.\n",
      "INFO:root:Received 156 observations in 0.70 seconds.\n",
      "INFO:root:Received 41 observations in 0.21 seconds.\n",
      "INFO:root:Received 55 observations in 0.78 seconds.\n",
      "INFO:root:Received 41 observations in 0.21 seconds.\n",
      "INFO:root:Received 14 observations in 0.14 seconds.\n",
      "INFO:root:Received 17 observations in 0.16 seconds.\n",
      "INFO:root:Received 55 observations in 0.52 seconds.\n",
      "INFO:root:Received 30 observations in 0.18 seconds.\n",
      "INFO:root:Received 17 observations in 0.16 seconds.\n",
      "INFO:root:Received 57 observations in 0.34 seconds.\n",
      "INFO:root:Received 38 observations in 0.30 seconds.\n",
      "INFO:root:Received 67 observations in 0.29 seconds.\n",
      "INFO:root:Received 31 observations in 0.44 seconds.\n",
      "INFO:root:Received 27 observations in 0.18 seconds.\n",
      "INFO:root:Received 61 observations in 0.34 seconds.\n",
      "INFO:root:Received 30 observations in 0.40 seconds.\n",
      "INFO:root:Received 42 observations in 0.16 seconds.\n",
      "INFO:root:Received 17 observations in 0.16 seconds.\n",
      "INFO:root:Received 45 observations in 0.20 seconds.\n",
      "INFO:root:Received 42 observations in 0.19 seconds.\n",
      "INFO:root:Received 31 observations in 0.15 seconds.\n",
      "INFO:root:Received 202 observations in 0.79 seconds.\n",
      "INFO:root:Received 28 observations in 0.17 seconds.\n",
      "INFO:root:Received 18 observations in 0.17 seconds.\n",
      "INFO:root:Received 66 observations in 0.57 seconds.\n",
      "INFO:root:Received 87 observations in 0.35 seconds.\n",
      "INFO:root:Received 28 observations in 0.38 seconds.\n",
      "INFO:root:Received 12 observations in 0.16 seconds.\n",
      "INFO:root:Received 21 observations in 0.17 seconds.\n",
      "INFO:root:Received 37 observations in 0.20 seconds.\n",
      "INFO:root:Received 41 observations in 0.19 seconds.\n",
      "INFO:root:Received 112 observations in 0.46 seconds.\n",
      "INFO:root:Received 51 observations in 0.48 seconds.\n",
      "INFO:root:Received 22 observations in 0.24 seconds.\n",
      "INFO:root:Received 48 observations in 0.20 seconds.\n",
      "INFO:root:Received 72 observations in 0.34 seconds.\n",
      "INFO:root:Received 42 observations in 0.38 seconds.\n",
      "INFO:root:Received 37 observations in 0.19 seconds.\n",
      "INFO:root:Received 96 observations in 0.45 seconds.\n",
      "INFO:root:Received 47 observations in 0.22 seconds.\n",
      "INFO:root:Received 33 observations in 0.18 seconds.\n",
      "INFO:root:Received 69 observations in 0.34 seconds.\n",
      "INFO:root:Received 57 observations in 0.31 seconds.\n",
      "INFO:root:Received 13 observations in 0.43 seconds.\n",
      "INFO:root:Received 42 observations in 0.19 seconds.\n",
      "INFO:root:Received 37 observations in 0.18 seconds.\n",
      "INFO:root:Received 56 observations in 0.33 seconds.\n",
      "INFO:root:Received 58 observations in 0.37 seconds.\n",
      "INFO:root:Received 153 observations in 0.63 seconds.\n",
      "INFO:root:Received 33 observations in 0.18 seconds.\n",
      "INFO:root:Received 38 observations in 0.16 seconds.\n",
      "INFO:root:Received 41 observations in 0.19 seconds.\n",
      "INFO:root:Received 38 observations in 0.18 seconds.\n",
      "INFO:root:Received 65 observations in 0.32 seconds.\n",
      "INFO:root:Received 42 observations in 0.36 seconds.\n",
      "INFO:root:Received 50 observations in 0.20 seconds.\n",
      "INFO:root:Received 135 observations in 0.51 seconds.\n",
      "INFO:root:Received 38 observations in 0.20 seconds.\n",
      "INFO:root:Received 25 observations in 0.17 seconds.\n",
      "INFO:root:Received 79 observations in 0.33 seconds.\n",
      "INFO:root:Received 42 observations in 0.37 seconds.\n",
      "INFO:root:Received 37 observations in 0.19 seconds.\n",
      "INFO:root:Received 165 observations in 0.88 seconds.\n",
      "INFO:root:Received 43 observations in 0.22 seconds.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:root:Received 95 observations in 0.45 seconds.\n",
      "INFO:root:Received 41 observations in 0.19 seconds.\n",
      "INFO:root:Received 30 observations in 0.18 seconds.\n",
      "INFO:root:Received 32 observations in 0.18 seconds.\n",
      "INFO:root:Received 30 observations in 0.22 seconds.\n",
      "INFO:root:Received 52 observations in 0.31 seconds.\n",
      "INFO:root:Received 35 observations in 0.18 seconds.\n",
      "INFO:root:Received 31 observations in 0.64 seconds.\n",
      "INFO:root:Received 29 observations in 0.17 seconds.\n",
      "INFO:root:Received 49 observations in 0.21 seconds.\n",
      "INFO:root:Received 60 observations in 0.31 seconds.\n",
      "INFO:root:Received 21 observations in 0.31 seconds.\n",
      "INFO:root:Received 163 observations in 0.64 seconds.\n",
      "INFO:root:Received 48 observations in 0.28 seconds.\n",
      "INFO:root:Received 74 observations in 0.33 seconds.\n",
      "INFO:root:Received 56 observations in 0.40 seconds.\n",
      "INFO:root:Received 41 observations in 0.21 seconds.\n",
      "INFO:root:Received 130 observations in 0.49 seconds.\n",
      "INFO:root:Received 73 observations in 0.54 seconds.\n",
      "INFO:root:Received 45 observations in 0.20 seconds.\n",
      "INFO:root:Received 38 observations in 0.19 seconds.\n",
      "INFO:root:Received 154 observations in 0.66 seconds.\n",
      "INFO:root:Received 22 observations in 0.36 seconds.\n",
      "INFO:root:Received 48 observations in 0.27 seconds.\n",
      "INFO:root:Received 63 observations in 0.32 seconds.\n",
      "INFO:root:Received 30 observations in 0.19 seconds.\n",
      "INFO:root:Received 99 observations in 0.35 seconds.\n",
      "INFO:root:Received 64 observations in 0.32 seconds.\n",
      "INFO:root:Received 13 observations in 0.16 seconds.\n",
      "INFO:root:Received 42 observations in 0.16 seconds.\n",
      "INFO:root:Received 41 observations in 0.20 seconds.\n",
      "INFO:root:Received 37 observations in 0.19 seconds.\n",
      "INFO:root:Received 43 observations in 0.19 seconds.\n",
      "INFO:root:Received 139 observations in 0.50 seconds.\n",
      "INFO:root:Received 90 observations in 0.34 seconds.\n",
      "INFO:root:Received 81 observations in 0.32 seconds.\n",
      "INFO:root:Received 52 observations in 0.31 seconds.\n",
      "INFO:root:Received 46 observations in 0.19 seconds.\n",
      "INFO:root:Received 25 observations in 0.18 seconds.\n",
      "INFO:root:Received 66 observations in 0.33 seconds.\n",
      "INFO:root:Received 31 observations in 0.29 seconds.\n",
      "INFO:root:Received 33 observations in 0.18 seconds.\n",
      "INFO:root:Received 50 observations in 0.29 seconds.\n",
      "INFO:root:Received 22 observations in 0.16 seconds.\n",
      "INFO:root:Received 150 observations in 0.56 seconds.\n",
      "INFO:root:Received 214 observations in 0.80 seconds.\n",
      "INFO:root:Received 49 observations in 0.24 seconds.\n",
      "INFO:root:Received 60 observations in 0.32 seconds.\n",
      "INFO:root:Received 21 observations in 0.30 seconds.\n",
      "INFO:root:Received 159 observations in 0.62 seconds.\n",
      "INFO:root:Received 24 observations in 0.29 seconds.\n",
      "INFO:root:Received 33 observations in 0.19 seconds.\n",
      "INFO:root:Received 167 observations in 0.83 seconds.\n",
      "INFO:root:Received 221 observations in 0.79 seconds.\n",
      "INFO:root:Received 34 observations in 0.17 seconds.\n",
      "INFO:root:Received 48 observations in 0.19 seconds.\n",
      "INFO:root:Received 80 observations in 0.33 seconds.\n",
      "INFO:root:Received 12 observations in 0.13 seconds.\n",
      "INFO:root:Received 55 observations in 0.30 seconds.\n",
      "INFO:root:Received 51 observations in 0.30 seconds.\n",
      "INFO:root:Received 42 observations in 0.19 seconds.\n",
      "INFO:root:Received 48 observations in 0.19 seconds.\n",
      "INFO:root:Received 111 observations in 0.46 seconds.\n",
      "INFO:root:Received 13 observations in 0.26 seconds.\n",
      "INFO:root:Received 41 observations in 0.52 seconds.\n",
      "INFO:root:Received 38 observations in 0.19 seconds.\n",
      "INFO:root:Received 17 observations in 0.16 seconds.\n",
      "INFO:root:Received 55 observations in 0.32 seconds.\n",
      "INFO:root:Received 41 observations in 0.19 seconds.\n",
      "INFO:root:Received 59 observations in 0.33 seconds.\n",
      "INFO:root:Received 26 observations in 0.17 seconds.\n",
      "INFO:root:Received 25 observations in 0.18 seconds.\n",
      "INFO:root:Received 16 observations in 0.20 seconds.\n",
      "INFO:root:Received 125 observations in 0.60 seconds.\n",
      "INFO:root:Received 48 observations in 0.21 seconds.\n",
      "INFO:root:Received 42 observations in 0.19 seconds.\n",
      "INFO:root:Received 25 observations in 0.17 seconds.\n",
      "INFO:root:Received 126 observations in 0.48 seconds.\n",
      "INFO:root:Received 57 observations in 0.31 seconds.\n",
      "INFO:root:Received 145 observations in 0.52 seconds.\n",
      "INFO:root:Received 23 observations in 0.16 seconds.\n",
      "INFO:root:Received 65 observations in 0.33 seconds.\n",
      "INFO:root:Received 25 observations in 0.17 seconds.\n",
      "INFO:root:Received 25 observations in 0.17 seconds.\n",
      "INFO:root:Received 43 observations in 0.17 seconds.\n",
      "INFO:root:Received 53 observations in 0.32 seconds.\n",
      "INFO:root:Received 67 observations in 0.34 seconds.\n",
      "INFO:root:Received 30 observations in 0.31 seconds.\n",
      "INFO:root:Received 204 observations in 0.80 seconds.\n",
      "INFO:root:Received 72 observations in 0.34 seconds.\n",
      "INFO:root:Received 39 observations in 0.18 seconds.\n",
      "INFO:root:Received 115 observations in 0.48 seconds.\n",
      "INFO:root:Received 17 observations in 0.16 seconds.\n",
      "INFO:root:Received 43 observations in 0.19 seconds.\n",
      "INFO:root:Received 29 observations in 0.17 seconds.\n",
      "INFO:root:Received 43 observations in 0.19 seconds.\n",
      "INFO:root:Received 21 observations in 0.17 seconds.\n",
      "INFO:root:Received 149 observations in 0.55 seconds.\n",
      "INFO:root:Received 157 observations in 0.63 seconds.\n",
      "INFO:root:Received 30 observations in 0.18 seconds.\n",
      "INFO:root:Received 100 observations in 0.35 seconds.\n",
      "INFO:root:Received 44 observations in 0.20 seconds.\n",
      "INFO:root:Received 12 observations in 0.14 seconds.\n",
      "INFO:root:Received 120 observations in 0.50 seconds.\n",
      "INFO:root:Received 37 observations in 0.18 seconds.\n",
      "INFO:root:Received 30 observations in 0.18 seconds.\n",
      "INFO:root:Received 37 observations in 0.19 seconds.\n",
      "INFO:root:Received 48 observations in 0.17 seconds.\n",
      "INFO:root:Received 25 observations in 0.18 seconds.\n",
      "INFO:root:Received 148 observations in 0.73 seconds.\n",
      "INFO:root:Received 44 observations in 0.20 seconds.\n",
      "INFO:root:Received 54 observations in 0.32 seconds.\n",
      "INFO:root:Received 242 observations in 0.88 seconds.\n",
      "INFO:root:Received 38 observations in 0.16 seconds.\n",
      "INFO:root:Received 38 observations in 0.18 seconds.\n",
      "INFO:root:Received 57 observations in 0.33 seconds.\n",
      "INFO:root:Received 164 observations in 0.63 seconds.\n",
      "INFO:root:Received 51 observations in 0.35 seconds.\n",
      "INFO:root:Received 72 observations in 0.36 seconds.\n",
      "INFO:root:Received 21 observations in 0.16 seconds.\n",
      "INFO:root:Received 37 observations in 0.19 seconds.\n",
      "INFO:root:Received 47 observations in 0.17 seconds.\n",
      "INFO:root:Received 156 observations in 1.08 seconds.\n",
      "INFO:root:Received 46 observations in 0.19 seconds.\n",
      "INFO:root:Received 38 observations in 0.18 seconds.\n",
      "INFO:root:Received 37 observations in 0.18 seconds.\n",
      "INFO:root:Received 61 observations in 0.30 seconds.\n",
      "INFO:root:Received 37 observations in 0.26 seconds.\n",
      "INFO:root:Received 17 observations in 0.17 seconds.\n",
      "INFO:root:Received 167 observations in 0.60 seconds.\n",
      "INFO:root:Received 254 observations in 1.16 seconds.\n",
      "INFO:root:Received 26 observations in 0.21 seconds.\n",
      "INFO:root:Received 182 observations in 0.65 seconds.\n",
      "INFO:root:Received 37 observations in 0.27 seconds.\n",
      "INFO:root:Received 73 observations in 0.32 seconds.\n",
      "INFO:root:Received 35 observations in 0.29 seconds.\n",
      "INFO:root:Received 59 observations in 0.28 seconds.\n",
      "INFO:root:Received 55 observations in 0.44 seconds.\n",
      "INFO:root:Received 49 observations in 0.20 seconds.\n",
      "INFO:root:Received 25 observations in 0.18 seconds.\n",
      "INFO:root:Received 52 observations in 0.32 seconds.\n",
      "INFO:root:Received 32 observations in 0.42 seconds.\n",
      "INFO:root:Received 43 observations in 0.18 seconds.\n",
      "INFO:root:Received 69 observations in 0.33 seconds.\n",
      "INFO:root:Received 41 observations in 0.41 seconds.\n",
      "INFO:root:Received 203 observations in 0.76 seconds.\n",
      "INFO:root:Received 34 observations in 0.18 seconds.\n",
      "INFO:root:Received 41 observations in 0.20 seconds.\n",
      "INFO:root:Received 30 observations in 0.19 seconds.\n",
      "INFO:root:Received 46 observations in 0.16 seconds.\n",
      "INFO:root:Received 53 observations in 0.33 seconds.\n",
      "INFO:root:Received 62 observations in 0.45 seconds.\n",
      "INFO:root:Received 30 observations in 0.18 seconds.\n",
      "INFO:root:Received 154 observations in 0.62 seconds.\n",
      "INFO:root:Received 38 observations in 0.30 seconds.\n",
      "INFO:root:Received 165 observations in 0.64 seconds.\n",
      "INFO:root:Received 157 observations in 0.70 seconds.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:root:Received 28 observations in 0.20 seconds.\n",
      "INFO:root:Received 73 observations in 0.61 seconds.\n",
      "INFO:root:Received 43 observations in 0.31 seconds.\n",
      "INFO:root:Received 74 observations in 0.30 seconds.\n",
      "INFO:root:Received 139 observations in 0.62 seconds.\n",
      "INFO:root:Received 21 observations in 0.16 seconds.\n",
      "INFO:root:Received 30 observations in 0.15 seconds.\n",
      "INFO:root:Received 49 observations in 0.19 seconds.\n",
      "INFO:root:Received 54 observations in 0.30 seconds.\n",
      "INFO:root:Received 52 observations in 0.52 seconds.\n",
      "INFO:root:Received 49 observations in 0.20 seconds.\n",
      "INFO:root:Received 33 observations in 0.19 seconds.\n",
      "INFO:root:Received 17 observations in 0.16 seconds.\n",
      "INFO:root:Received 69 observations in 0.31 seconds.\n",
      "INFO:root:Received 104 observations in 0.54 seconds.\n",
      "INFO:root:Received 61 observations in 0.44 seconds.\n",
      "INFO:root:Received 29 observations in 0.21 seconds.\n",
      "INFO:root:Received 41 observations in 0.20 seconds.\n",
      "INFO:root:Received 39 observations in 0.18 seconds.\n",
      "INFO:root:Received 41 observations in 0.19 seconds.\n",
      "INFO:root:Received 52 observations in 0.32 seconds.\n",
      "INFO:root:Received 102 observations in 0.86 seconds.\n",
      "INFO:root:Received 37 observations in 0.39 seconds.\n",
      "INFO:root:Received 254 observations in 0.92 seconds.\n",
      "INFO:root:Received 48 observations in 0.31 seconds.\n",
      "INFO:root:Received 107 observations in 0.57 seconds.\n",
      "INFO:root:Received 50 observations in 0.35 seconds.\n",
      "INFO:root:Received 54 observations in 0.30 seconds.\n",
      "INFO:root:Received 160 observations in 0.68 seconds.\n",
      "INFO:root:Received 50 observations in 0.25 seconds.\n",
      "INFO:root:Received 89 observations in 0.34 seconds.\n",
      "INFO:root:Received 58 observations in 0.31 seconds.\n",
      "INFO:root:Received 49 observations in 0.27 seconds.\n",
      "INFO:root:Received 26 observations in 0.17 seconds.\n",
      "INFO:root:Received 32 observations in 0.15 seconds.\n",
      "INFO:root:Received 62 observations in 0.31 seconds.\n",
      "INFO:root:Received 20 observations in 0.28 seconds.\n",
      "INFO:root:Received 41 observations in 0.18 seconds.\n",
      "INFO:root:Received 165 observations in 0.65 seconds.\n",
      "INFO:root:Received 46 observations in 0.39 seconds.\n",
      "INFO:root:Received 108 observations in 0.47 seconds.\n",
      "INFO:root:Received 30 observations in 0.45 seconds.\n",
      "INFO:root:Received 153 observations in 0.62 seconds.\n",
      "INFO:root:Received 144 observations in 0.61 seconds.\n",
      "INFO:root:Received 41 observations in 0.19 seconds.\n",
      "INFO:root:Received 58 observations in 0.33 seconds.\n",
      "INFO:root:Received 38 observations in 0.36 seconds.\n",
      "INFO:root:Received 157 observations in 0.60 seconds.\n",
      "INFO:root:Received 30 observations in 0.15 seconds.\n",
      "INFO:root:Received 25 observations in 0.17 seconds.\n",
      "INFO:root:Received 195 observations in 0.81 seconds.\n",
      "INFO:root:Received 44 observations in 0.17 seconds.\n",
      "INFO:root:Received 222 observations in 0.80 seconds.\n",
      "INFO:root:Received 55 observations in 0.38 seconds.\n",
      "INFO:root:Received 26 observations in 0.17 seconds.\n",
      "INFO:root:Received 18 observations in 0.17 seconds.\n",
      "INFO:root:Received 57 observations in 0.29 seconds.\n",
      "INFO:root:Received 57 observations in 0.44 seconds.\n",
      "INFO:root:Received 54 observations in 0.31 seconds.\n",
      "INFO:root:Received 35 observations in 0.18 seconds.\n",
      "INFO:root:Received 47 observations in 0.19 seconds.\n",
      "INFO:root:Received 139 observations in 0.49 seconds.\n",
      "INFO:root:Received 79 observations in 0.33 seconds.\n",
      "INFO:root:Received 17 observations in 0.20 seconds.\n",
      "INFO:root:Received 30 observations in 0.17 seconds.\n",
      "INFO:root:Received 30 observations in 0.18 seconds.\n",
      "INFO:root:Received 65 observations in 0.39 seconds.\n",
      "INFO:root:Received 139 observations in 0.49 seconds.\n",
      "INFO:root:Received 211 observations in 0.77 seconds.\n",
      "INFO:root:Received 33 observations in 0.28 seconds.\n",
      "INFO:root:Received 20 observations in 0.47 seconds.\n",
      "INFO:root:Received 54 observations in 0.31 seconds.\n",
      "INFO:root:Received 53 observations in 0.41 seconds.\n",
      "INFO:root:Received 163 observations in 0.62 seconds.\n",
      "INFO:root:Received 69 observations in 0.33 seconds.\n",
      "INFO:root:Received 27 observations in 0.17 seconds.\n",
      "INFO:root:Received 102 observations in 0.43 seconds.\n",
      "INFO:root:Received 42 observations in 0.19 seconds.\n",
      "INFO:root:Received 29 observations in 0.19 seconds.\n",
      "INFO:root:Received 181 observations in 0.90 seconds.\n",
      "INFO:root:Received 154 observations in 0.67 seconds.\n",
      "INFO:root:Received 73 observations in 0.51 seconds.\n",
      "INFO:root:Received 25 observations in 0.17 seconds.\n",
      "INFO:root:Received 64 observations in 0.33 seconds.\n",
      "INFO:root:Received 79 observations in 0.41 seconds.\n",
      "INFO:root:Received 17 observations in 0.48 seconds.\n",
      "INFO:root:Received 42 observations in 0.92 seconds.\n",
      "INFO:root:Received 43 observations in 0.18 seconds.\n",
      "INFO:root:Received 36 observations in 0.18 seconds.\n",
      "INFO:root:Received 38 observations in 0.18 seconds.\n",
      "INFO:root:Received 31 observations in 0.17 seconds.\n",
      "INFO:root:Received 58 observations in 0.32 seconds.\n",
      "INFO:root:Received 27 observations in 0.19 seconds.\n",
      "INFO:root:Received 25 observations in 0.18 seconds.\n",
      "INFO:root:Received 34 observations in 0.18 seconds.\n",
      "INFO:root:Received 157 observations in 0.59 seconds.\n",
      "INFO:root:Received 44 observations in 0.27 seconds.\n",
      "INFO:root:Received 49 observations in 0.20 seconds.\n",
      "INFO:root:Received 139 observations in 0.81 seconds.\n",
      "INFO:root:Received 572 patients in 205.73 seconds.\n"
     ]
    }
   ],
   "source": [
    "# Get patients by condition\n",
    "patients_by_condition_text = client.get_patients_by_condition_text(\"Acute viral pharyngitis\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of pandas failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/__init__.py\", line 52, in <module>\n",
      "    import pandas.arrays\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/arrays/__init__.py\", line 6, in <module>\n",
      "    from pandas.core.arrays import (\n",
      "ImportError: cannot import name 'IntervalArray' from 'pandas.core.arrays' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/__init__.py)\n",
      "]\n",
      "[autoreload of pandas._libs failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/__init__.py\", line 4, in <module>\n",
      "    from .tslibs import (\n",
      "ImportError: cannot import name 'iNaT' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas._libs.tslibs failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py\", line 4, in <module>\n",
      "    from .conversion import normalize_date, localize_pydatetime, tz_convert_single\n",
      "ImportError: cannot import name 'normalize_date' from 'pandas._libs.tslibs.conversion' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/conversion.cpython-37m-darwin.so)\n",
      "]\n",
      "[autoreload of pandas.core.config_init failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/config_init.py\", line 50, in <module>\n",
      "    validator=is_bool, cb=use_bottleneck_cb)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/config.py\", line 728, in inner\n",
      "    _register_option = register_option\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/config.py\", line 443, in register_option\n",
      "pandas.core.config.OptionError: \"Option 'compute.use_bottleneck' has already been registered\"\n",
      "]\n",
      "[autoreload of pandas.core.config failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 392, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 329, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 265, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: inner() requires a code object with 2 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.api failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/api.py\", line 7, in <module>\n",
      "    from pandas.core.arrays.integer import (\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/integer.py\", line 16, in <module>\n",
      "    from pandas.core.dtypes.dtypes import register_extension_dtype\n",
      "ImportError: cannot import name 'register_extension_dtype' from 'pandas.core.dtypes.dtypes' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/dtypes.py)\n",
      "]\n",
      "[autoreload of pandas.core.algorithms failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/algorithms.py\", line 18, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_float64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.dtypes.cast failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/cast.py\", line 8, in <module>\n",
      "    from pandas._libs.tslibs import NaT, OutOfBoundsDatetime, Period, iNaT\n",
      "ImportError: cannot import name 'NaT' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.dtypes.common failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py\", line 10, in <module>\n",
      "    from pandas.core.dtypes.dtypes import (\n",
      "ImportError: cannot import name 'registry' from 'pandas.core.dtypes.dtypes' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/dtypes.py)\n",
      "]\n",
      "[autoreload of pandas.core.dtypes.dtypes failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/dtypes.py\", line 9, in <module>\n",
      "    from pandas._libs.tslibs import NaT, Period, Timestamp, timezones\n",
      "ImportError: cannot import name 'NaT' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.errors failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/errors/__init__.py\", line 7, in <module>\n",
      "    from pandas._libs.tslibs import OutOfBoundsDatetime\n",
      "ImportError: cannot import name 'OutOfBoundsDatetime' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.dtypes.missing failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/missing.py\", line 7, in <module>\n",
      "    from pandas._libs.tslibs import NaT, iNaT\n",
      "ImportError: cannot import name 'NaT' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/__init__.py\", line 1, in <module>\n",
      "    from .array_ import array  # noqa\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/array_.py\", line 5, in <module>\n",
      "    from pandas.core.dtypes.dtypes import registry\n",
      "ImportError: cannot import name 'registry' from 'pandas.core.dtypes.dtypes' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/dtypes.py)\n",
      "]\n",
      "[autoreload of pandas.core.arrays.categorical failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/categorical.py\", line 18, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_int64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.base failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 392, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 329, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 287, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 329, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 265, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: searchsorted() requires a code object with 5 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.nanops failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/nanops.py\", line 54, in <module>\n",
      "    set_use_bottleneck(get_option('compute.use_bottleneck'))\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/config.py\", line 227, in __call__\n",
      "    return self.__func__(*args, **kwds)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/config.py\", line 97, in _get_option\n",
      "    key = _get_single_key(pat, silent)\n",
      "pandas.core.config.OptionError: \"No such keys(s): 'compute.use_bottleneck'\"\n",
      "]\n",
      "[autoreload of pandas.core.missing failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/missing.py\", line 13, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_float64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.groupby failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/groupby/__init__.py\", line 2, in <module>\n",
      "    from pandas.core.groupby.generic import (  # noqa: F401\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/groupby/generic.py\", line 25, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_int64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.groupby.groupby failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/groupby/groupby.py\", line 28, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_float' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.api failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/api.py\", line 7, in <module>\n",
      "    from pandas.core.indexes.base import (\n",
      "ImportError: cannot import name 'ensure_index' from 'pandas.core.indexes.base' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/base.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.base failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/base.py\", line 17, in <module>\n",
      "    from pandas.core.dtypes.cast import maybe_cast_to_integer_array\n",
      "ImportError: cannot import name 'maybe_cast_to_integer_array' from 'pandas.core.dtypes.cast' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/cast.py)\n",
      "]\n",
      "[autoreload of pandas.tseries.offsets failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/tseries/offsets.py\", line 9, in <module>\n",
      "    from pandas._libs.tslibs import (\n",
      "ImportError: cannot import name 'NaT' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.tools.datetimes failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/tools/datetimes.py\", line 7, in <module>\n",
      "    from pandas._libs.tslibs import Timestamp, conversion, parsing\n",
      "ImportError: cannot import name 'Timestamp' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.tseries.frequencies failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/tseries/frequencies.py\", line 8, in <module>\n",
      "    from pandas._libs.algos import unique_deltas\n",
      "ImportError: cannot import name 'unique_deltas' from 'pandas._libs.algos' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/algos.cpython-37m-darwin.so)\n",
      "]\n",
      "[autoreload of pandas.core.ops failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/ops.py\", line 25, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_object' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.frozen failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 392, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 329, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 287, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 329, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 265, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: searchsorted() requires a code object with 1 free vars, not 5\n",
      "]\n",
      "[autoreload of pandas.core.sorting failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/sorting.py\", line 11, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_int64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.strings failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/strings.py\", line 15, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_object' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.category failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/category.py\", line 11, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_platform_int' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.multi failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/multi.py\", line 17, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_int64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.interval failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/interval.py\", line 16, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_platform_int' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.datetimes failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py\", line 16, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_int64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.datetimelike failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/datetimelike.py\", line 15, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_int64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.tools.timedeltas failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/tools/timedeltas.py\", line 7, in <module>\n",
      "    from pandas._libs.tslibs.timedeltas import Timedelta, parse_timedelta_unit\n",
      "ImportError: cannot import name 'parse_timedelta_unit' from 'pandas._libs.tslibs.timedeltas' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/timedeltas.cpython-37m-darwin.so)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.timedeltas failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/timedeltas.py\", line 12, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_int64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.range failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 392, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 329, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 287, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 329, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 265, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: union() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.indexes.period failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/period.py\", line 8, in <module>\n",
      "    from pandas._libs.tslibs import (\n",
      "ImportError: cannot import name 'NaT' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.frame failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/frame.py\", line 51, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'infer_dtype_from_object' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.generic failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/generic.py\", line 26, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_int64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexing failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexing.py\", line 13, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_platform_int' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.io.formats.format failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/io/formats/format.py\", line 15, in <module>\n",
      "    from pandas._libs.tslibs import NaT, Timedelta, Timestamp, iNaT\n",
      "ImportError: cannot import name 'NaT' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.series failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/series.py\", line 18, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_platform_int' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.accessors failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/indexes/accessors.py\", line 14, in <module>\n",
      "    from pandas.core.arrays import DatetimeArray, PeriodArray, TimedeltaArray\n",
      "ImportError: cannot import name 'DatetimeArray' from 'pandas.core.arrays' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.window failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/window.py\", line 19, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_float64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.panel failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/panel.py\", line 26, in <module>\n",
      "    from pandas.core.index import (\n",
      "ImportError: cannot import name 'ensure_index' from 'pandas.core.index' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/index.py)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.reshape failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/reshape/reshape.py\", line 13, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_platform_int' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.sparse.api failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/sparse/api.py\", line 3, in <module>\n",
      "    from pandas.core.arrays.sparse import SparseArray, SparseDtype\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/sparse.py\", line 16, in <module>\n",
      "    from pandas._libs.tslibs import NaT\n",
      "ImportError: cannot import name 'NaT' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.sparse.series failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/sparse/series.py\", line 24, in <module>\n",
      "    from pandas.core.arrays import SparseArray\n",
      "ImportError: cannot import name 'SparseArray' from 'pandas.core.arrays' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.core.sparse.frame failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/sparse/frame.py\", line 18, in <module>\n",
      "    from pandas.core.dtypes.common import ensure_platform_int, is_scipy_sparse\n",
      "ImportError: cannot import name 'ensure_platform_int' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.tools.numeric failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/tools/numeric.py\", line 6, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_object' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.api failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/reshape/api.py\", line 6, in <module>\n",
      "    from pandas.core.reshape.pivot import crosstab, pivot, pivot_table\n",
      "ImportError: cannot import name 'pivot' from 'pandas.core.reshape.pivot' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/reshape/pivot.py)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.concat failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/reshape/concat.py\", line 14, in <module>\n",
      "    from pandas.core.index import (\n",
      "ImportError: cannot import name 'ensure_index' from 'pandas.core.index' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/index.py)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.merge failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/reshape/merge.py\", line 17, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_float64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.core.reshape.pivot failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/reshape/pivot.py\", line 368, in <module>\n",
      "    @Appender(_shared_docs['pivot'], indents=1)\n",
      "KeyError: 'pivot'\n",
      "]\n",
      "[autoreload of pandas.core.reshape.tile failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/reshape/tile.py\", line 10, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_int64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.io.parsers failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/io/parsers.py\", line 29, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_object' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.io.pytables failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/io/pytables.py\", line 23, in <module>\n",
      "    from pandas.core.dtypes.common import (\n",
      "ImportError: cannot import name 'ensure_int64' from 'pandas.core.dtypes.common' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/dtypes/common.py)\n",
      "]\n",
      "[autoreload of pandas.io.json failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/io/json/__init__.py\", line 5, in <module>\n",
      "    del json, normalize, table_schema  # noqa\n",
      "NameError: name 'json' is not defined\n",
      "]\n",
      "[autoreload of pandas.io.json.json failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/io/json/json.py\", line 8, in <module>\n",
      "    from pandas._libs.tslibs import iNaT\n",
      "ImportError: cannot import name 'iNaT' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.api.extensions failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/api/extensions/__init__.py\", line 6, in <module>\n",
      "    from pandas.core.arrays import (ExtensionArray,    # noqa\n",
      "ImportError: cannot import name 'ExtensionScalarOpsMixin' from 'pandas.core.arrays' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.io.feather_format failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 392, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 329, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 265, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: read_feather() requires a code object with 0 free vars, not 5\n",
      "]\n",
      "[autoreload of pandas.io.stata failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/io/stata.py\", line 24, in <module>\n",
      "    from pandas._libs.tslibs import NaT, Timestamp\n",
      "ImportError: cannot import name 'NaT' from 'pandas._libs.tslibs' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py)\n",
      "]\n",
      "[autoreload of pandas.io.packers failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/io/packers.py\", line 64, in <module>\n",
      "    from pandas.core.arrays import DatetimeArray, IntervalArray, PeriodArray\n",
      "ImportError: cannot import name 'DatetimeArray' from 'pandas.core.arrays' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/__init__.py)\n",
      "]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of pandas.util.testing failed: Traceback (most recent call last):\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 376, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/imp.py\", line 315, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/util/testing.py\", line 38, in <module>\n",
      "    from pandas.core.arrays import (\n",
      "ImportError: cannot import name 'DatetimeArray' from 'pandas.core.arrays' (/Users/bockc/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/pandas/core/arrays/__init__.py)\n",
      "]\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'FHIRClient' object has no attribute 'get_patients_by_code'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-10-52549065200c>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mclient\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_patients_by_code\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'183450002'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m: 'FHIRClient' object has no attribute 'get_patients_by_code'"
     ]
    }
   ],
   "source": [
    "c = client.get_patients_by_code('183450002')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:root:Received 154 observations in 0.96 seconds.\n",
      "INFO:root:Received 59 observations in 0.51 seconds.\n",
      "INFO:root:Received 162 observations in 1.30 seconds.\n",
      "INFO:root:Received 206 observations in 1.26 seconds.\n",
      "INFO:root:Received 4 patients in 4.53 seconds.\n"
     ]
    }
   ],
   "source": [
    "patients_by_condition_text = client.get_patients_by_condition_text(\"Abdominal pain\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(patients_by_condition_text)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Machine Learning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:root:Extracting attributes from data set\n",
      "INFO:root:Preprocessing data\n",
      "INFO:root:Started training of clf\n",
      "INFO:root:Training completed\n",
      "INFO:root:Accuracy : 1.0, F1-score : 1.0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Prediction accuracy 1.0\n"
     ]
    }
   ],
   "source": [
    "from ml_on_fhir import MLOnFHIRClassifier, MLOnFHIRCluster\n",
    "from fhir_objects.patient import Patient\n",
    "from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier\n",
    "from sklearn.svm import SVC\n",
    "\n",
    "ml_fhir = MLOnFHIRClassifier(Patient, feature_attrs=['birthDate'], label_attrs=['gender'], random_state=44)\n",
    "X, y, trained_clf = ml_fhir.fit(patients_by_condition_text, DecisionTreeClassifier())\n",
    "\n",
    "from sklearn.metrics import accuracy_score, roc_curve, auc\n",
    "fpr, tpr, _ = roc_curve(y, trained_clf.predict(X))\n",
    "print(\"Prediction accuracy {}\".format( auc(fpr, tpr) ) )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'accuracy': 1.0,\n",
       " 'f1_score': 1.0,\n",
       " 'precision': array([1., 1.]),\n",
       " 'recall': array([1., 1.]),\n",
       " 'f1_score_class': array([1., 1.]),\n",
       " 'support': array([2, 2]),\n",
       " 'AUROC': 1.0,\n",
       " 'AUPRC': 1.0,\n",
       " 'tn': 2,\n",
       " 'fp': 0,\n",
       " 'fn': 0,\n",
       " 'tp': 2}"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Evaluate classifier:\n",
    "ml_fhir.evaluate(X, y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "positional argument follows keyword argument (<ipython-input-8-174601a13492>, line 3)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-8-174601a13492>\"\u001b[0;36m, line \u001b[0;32m3\u001b[0m\n\u001b[0;31m    ml_fhir = MLOnFHIRCluster(Patient, feature_attrs=['birthDate'], label_attrs=['gender'], ra)\u001b[0m\n\u001b[0m                                                                                           ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m positional argument follows keyword argument\n"
     ]
    }
   ],
   "source": [
    "# Try clustering\n",
    "from sklearn.cluster import KMeans\n",
    "ml_fhir = MLOnFHIRCluster(Patient, feature_attrs=['birthDate'], label_attrs=['gender'], random_state=4)\n",
    "X, y, trained_cluster = ml_fhir.fit(patients_by_condition_text, KMeans(n_clusters=2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "-82005.33089398735"
      ]
     },
     "execution_count": 60,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "trained_cluster.score(X, y)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Experimental Section"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "super(type, obj): obj must be an instance or subtype of type",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-11-46b901ff2065>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     21\u001b[0m \u001b[0mlogger\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlogging\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetLogger\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m__name__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     22\u001b[0m \u001b[0mlogging\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbasicConfig\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlevel\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogging\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mINFO\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 23\u001b[0;31m \u001b[0mclient\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mFHIRClient\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mservice_base_url\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'https://r3.smarthealthit.org'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlogger\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogger\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpreprocessor\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mpreprocessing\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     24\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     25\u001b[0m \u001b[0mpatients_by_condition_text\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mclient\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_patients_by_condition_code\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msystem\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"http://snomed.info/sct\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcode\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'284549007'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Projects/ml-on-fhir/src/fhir_client.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, service_base_url, logger, preprocessor)\u001b[0m\n\u001b[1;32m     26\u001b[0m         \"\"\"\n\u001b[1;32m     27\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mserver_url\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mservice_base_url\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 28\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msession\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mrequests\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSession\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     29\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlogger\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlogger\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     30\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpreprocessor\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpreprocessor\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/requests/sessions.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    415\u001b[0m         \u001b[0;31m# Default connection adapters.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    416\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0madapters\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mOrderedDict\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 417\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmount\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'https://'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mHTTPAdapter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    418\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmount\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'http://'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mHTTPAdapter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    419\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/share/virtualenvs/ml-on-fhir-Fls4lXwQ/lib/python3.7/site-packages/requests/adapters.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, pool_connections, pool_maxsize, max_retries, pool_block)\u001b[0m\n\u001b[1;32m    121\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mproxy_manager\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    122\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 123\u001b[0;31m         \u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mHTTPAdapter\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__init__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    124\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    125\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_pool_connections\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpool_connections\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: super(type, obj): obj must be an instance or subtype of type"
     ]
    }
   ],
   "source": [
    "%autoreload 2\n",
    "\n",
    "import preprocessing\n",
    "from preprocessing import register_preprocessor, PatientProcessorFactory, get_coding_condition\n",
    "\n",
    "from sklearn.base import BaseEstimator\n",
    "import datetime as dt\n",
    "import numpy as np\n",
    "from fhir_objects.fhir_resources import date_format\n",
    "\n",
    "from fhir_client import FHIRClient\n",
    "import logging\n",
    "logging.basicConfig(level=logging.INFO)\n",
    "import pandas as pd\n",
    "\n",
    "from ml_on_fhir import MLOnFHIRClassifier\n",
    "from fhir_objects.patient import Patient\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "\n",
    "\n",
    "logger = logging.getLogger(__name__)\n",
    "logging.basicConfig(level=logging.INFO)\n",
    "client = FHIRClient(service_base_url='https://r3.smarthealthit.org', logger=logger, preprocessor=preprocessing)\n",
    "\n",
    "patients_by_condition_text = client.get_patients_by_condition_code(system=\"http://snomed.info/sct\", code='284549007')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[preprocessing.ObservationLatestBmiProcessor,\n",
       " preprocessing.ObservationLatestWeightProcessor,\n",
       " preprocessing.ObservationLatestHeightProcessor]"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "client._observation_preprocessors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "Module 'preprocessing' has no attribute PatientweightLatestProcessor. \n                    Feel free to implement your custom class in module 'preprocessing' with signature PatientweightLatestProcessor(BaseEstimator).\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m~/Projects/ml-on-fhir/src/ml_on_fhir.py\u001b[0m in \u001b[0;36mtransformers\u001b[0;34m(self, attrs)\u001b[0m\n\u001b[1;32m    108\u001b[0m                 self._transformers[fhir_attr] = getattr(\n\u001b[0;32m--> 109\u001b[0;31m                     preprocessing_module, class_name)()\n\u001b[0m\u001b[1;32m    110\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mAttributeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: module 'preprocessing' has no attribute 'PatientweightLatestProcessor'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-13-9838c3d164b4>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mml_fhir\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mMLOnFHIRClassifier\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mPatient\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeature_attrs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'weightLatest'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'heightLatest'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'bmiLatest'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlabel_attrs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'gender'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0mX\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtrained_clf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mml_fhir\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpatients_by_condition_text\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mDecisionTreeClassifier\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mX\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Projects/ml-on-fhir/src/ml_on_fhir.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, fhir_class, feature_attrs, label_attrs, random_state)\u001b[0m\n\u001b[1;32m    174\u001b[0m     \"\"\"\n\u001b[1;32m    175\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__init__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfhir_class\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mUnion\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mPatient\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeature_attrs\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mList\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlabel_attrs\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mList\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrandom_state\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mint\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m42\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 176\u001b[0;31m         \u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mMLOnFHIRClassifier\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__init__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfhir_class\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeature_attrs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlabel_attrs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrandom_state\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    177\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    178\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdata\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mList\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mUnion\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mPatient\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msklearn_clf\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mClassifierMixin\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mRandomForestClassifier\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Projects/ml-on-fhir/src/ml_on_fhir.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, fhir_class, feature_attrs, label_attrs, random_state)\u001b[0m\n\u001b[1;32m     38\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlabel_attrs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlabel_attrs\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     39\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfeature_attrs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfeature_attrs\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 40\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtransformers\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mfeature_attrs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlabel_attrs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     41\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrandom_state\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mrandom_state\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     42\u001b[0m         \u001b[0;31m# The easiest way to initiate sklearn random state globally is to set the np.random.seed(), although this might not be stable for\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Projects/ml-on-fhir/src/ml_on_fhir.py\u001b[0m in \u001b[0;36mtransformers\u001b[0;34m(self, attrs)\u001b[0m\n\u001b[1;32m    111\u001b[0m                 raise AttributeError(\"\"\"Module 'preprocessing' has no attribute {}. \n\u001b[1;32m    112\u001b[0m                     \u001b[0mFeel\u001b[0m \u001b[0mfree\u001b[0m \u001b[0mto\u001b[0m \u001b[0mimplement\u001b[0m \u001b[0myour\u001b[0m \u001b[0mcustom\u001b[0m \u001b[0;32mclass\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mmodule\u001b[0m \u001b[0;34m'preprocessing'\u001b[0m \u001b[0;32mwith\u001b[0m \u001b[0msignature\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mBaseEstimator\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 113\u001b[0;31m \"\"\".format(class_name, class_name))\n\u001b[0m\u001b[1;32m    114\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    115\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0mtransformers\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdeleter\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: Module 'preprocessing' has no attribute PatientweightLatestProcessor. \n                    Feel free to implement your custom class in module 'preprocessing' with signature PatientweightLatestProcessor(BaseEstimator).\n"
     ]
    }
   ],
   "source": [
    "\n",
    "ml_fhir = MLOnFHIRClassifier(Patient, feature_attrs=['weightLatest', 'heightLatest', 'bmiLatest'], label_attrs=['gender'])\n",
    "X, y, trained_clf = ml_fhir.fit(patients_by_condition_text, DecisionTreeClassifier())\n",
    "\n",
    "X"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "class PatientProcessorBaseClass(BaseEstimator):\n",
    "    \"\"\"\n",
    "    Base class that is used for the generation of Patient Processors \n",
    "    \"\"\"\n",
    "\n",
    "    def transform(self, X, **transform_params):\n",
    "        return X.astype(float)\n",
    "\n",
    "    def fit(self, X, y=None, **fit_params):\n",
    "        return self"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import Type\n",
    "def PatientProcessorFactory(class_name: str, base_class: Type[PatientProcessorBaseClass]=PatientProcessorBaseClass):\n",
    "    \"\"\"\n",
    "    Helper class to generate Patient Processor classes with specific names\n",
    "\n",
    "    Args:\n",
    "        class_name (str): Name of the class to be generated\n",
    "        base_class (class object): Base class \n",
    "    \"\"\"\n",
    "\n",
    "    new_cl = types.new_class(class_name, (base_class,))\n",
    "    c = new_cl()\n",
    "    print(c)\n",
    "    return new_Cl"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'types' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-16-6e35b198d450>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mPatientProcessorFactory\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'test'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m<ipython-input-15-4f486903661a>\u001b[0m in \u001b[0;36mPatientProcessorFactory\u001b[0;34m(class_name, base_class)\u001b[0m\n\u001b[1;32m      9\u001b[0m     \"\"\"\n\u001b[1;32m     10\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 11\u001b[0;31m     \u001b[0mnew_cl\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtypes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnew_class\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mclass_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mbase_class\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     12\u001b[0m     \u001b[0mc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnew_cl\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     13\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mc\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'types' is not defined"
     ]
    }
   ],
   "source": [
    "PatientProcessorFactory('test')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
